### ISSUE TITLE
关于Authorization 

### ISSUE THREAD

**Issue by unrealchenyu** [yilinyo/xhsnotesSearch#1]
能否分享下抓包的方法

**Comment by yilinyo** [comment]
方法一：下载低于3.6.3版的wechat windows版本最好是3.6.0.18，然后打开xhs 小程序 打开  fiddler 然后找到xhs 的https 请求 headers 里 Authorization 
![image](https://user-images.githubusercontent.com/88622778/231797670-4c7f5aae-6e95-45bc-8b3f-073ef7af5fa7.png)


方法二： IOS 版xhs 微信小程序可以用Thor之类软件的抓取依旧是抓 headers 里 Authorization ，使用IOS手机抓取 微信没有版本限制。

方法三：用蓝鸟之类的app抓安卓wx小程序xhs，没试过应该也可以

**Comment by unrealchenyu** [comment]
> fiddler
